spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka
  server:
    eviction-interval-timer-in-ms: 60000
    peer-node-connect-timeout-ms: 6000
    peer-node-read-timeout-ms: 6000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761